### ISSUE TITLE
여러 GitHub owner 지원

### ISSUE THREAD

**Issue by msk** [aicers/github-dashboard-server#57]
현재의 설정파일은 GitHub 저장소를 다음과 같이 지정하도록 되어 있어서, 한 owner에 속한 저장소들에서만 이슈를 가져올 수 있습니다.

```toml
[repository]
owner = "aicers"
names = ["github-dashboard-server", "github-dashboard-client"]
```

이를 TOML의 [Array of Tables](https://toml.io/en/v1.0.0#array-of-tables)를 쓰도록 다음과 같이 바꾸어, 저장소별로 다른 owner를 지정할 수 있도록 합니다.

```toml
[[repositories]]
owner = "aicers"
name = "github-dashboard-server"

[[repositories]]
owner = "aicers"
name = "github-dashboard-client"
```

구현할 때는 `conf::Config`, `conf::RepoInfo`를 위의 TOML 파일에 맞게 변경하고, 거기에 맞도록 코드를 고쳐주면 됩니다.
